version: "3.7"

services:
  postgres:
    image: postgres
    container_name: postgres_container
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: root
      POSTGRES_DB: cnpj_base
    ports:
      - "5432:5432"
    volumes:
      - ./db:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5500:80"
    depends_on:
      - postgres

  app:
    build:
      context: .
      dockerfile: Dockerfile 
    ports: 
      - "5000:5000"
    volumes:
      - ./src:/usr/src
      - ./data-csv:/usr/data_csv
    depends_on:
      - postgres

